# Generated by Django 5.1.4 on 2024-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.CharField(default='Income', max_length=150),
        ),
    ]
